apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  # 1 - CLUSTER SETTINGS
  CONFLUENT_LICENSE: "developer"
  KAFKA_KRAFT_MODE: "true"
  KAFKA_NODE_ID: "1"
  CLUSTER_ID: "5AZNAGG6SZOLY6S4Xw8dJw"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

  # 2 - LISTENER CONFIGURATIONS
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:29092"
  KAFKA_CLASSPATH: "/usr/share/java/*"

  # 3 - CLUSTER LEVEL TOPIC CONFIGURATIONS
  KAFKA_CLEANUP_POLICY: "delete,compact"
  KAFKA_COMPRESSION_TYPE: "lz4"
  KAFKA_COMPRESSION_LZ4_LEVEL: "4"
  KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: "86400000"
  KAFKA_FILE_DELETE_DELAY_MS: "120000"
  KAFKA_INDEX_INTERVAL_BYTES: ""
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_LOG_RETENTION_BYES: ""
  KAFKA_FLUSH_MESSAGES: "10000"
  KAFKA_LOG_FLUSH_INTERVAL_MS: "300000"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_LOG4J_LOGGERS: "org.apache.kafka=DEBUG,org.apache.kafka.connect=DEBUG"

  # JMX CONFIGURATIONS
  KAFKA_JMX_PORT: "9101"
  KAFKA_JMX_HOSTNAME: "kafka"
  KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9101 -Dcom.sun.management.jmxremote.rmi.port=9101 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=kafka"
  JMX_PROMETHEUS_EXPORTER_PORT: "9101"
