---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
    - name: jmx
      port: 9101
      targetPort: 9101
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - name: external
      port: 29092
      targetPort: 29092
      # nodePort: 31292  # Optional: specify a static NodePort if required.
  selector:
    app: kafka
