services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      one-network-to-rule-them-all:
      
networks:
  one-network-to-rule-them-all:
    external: true