
services:
  
  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.0
    ports:
      - 3000:3000  # Grafana UI will be accessible at http://localhost:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
      
    networks:
      one-network-to-rule-them-all:

networks:
  one-network-to-rule-them-all:
    external: true